# Site settings
title: Yoolk Liquid
email: chamnap@yoolk.com
description: > # this means to ignore newlines until "baseurl:"
  Yoolk InstantWebsite Liquid Documentation
url: 'https://yoolk.github.io'
baseurl: '/liquid-documentation'
twitter_username: yoolk
github_username:  yoolk

# Build settings
markdown: kramdown